# Nombre del workflow que aparecerá en la pestaña "Actions" de GitHub
name: CI-CD Pipeline

# Define el disparador (trigger) del workflow
on:
  push:
    branches: [ "main" ]

# Define los trabajos (jobs) que se ejecutarán
jobs:
  build-and-push-docker-image:
    # El tipo de máquina virtual en la que se ejecutará el job
    runs-on: ubuntu-latest

    # Los pasos que componen el job
    steps:
      # Paso 1: Clona el código del repositorio a la máquina virtual
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- NUEVOS PASOS ---
      # Paso 2: Configurar Python para ejecutar el script ETL
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Paso 3: Instalar dependencias de Python desde requirements.txt
      - name: Install Python dependencies
        run: pip install -r requirements.txt

      # Paso 4: Ejecutar el script ETL para crear el archivo restaurants.db
      - name: Run ETL script to create database
        run: python app/etl.py
      # --- FIN DE NUEVOS PASOS ---

      # Paso 5: Inicia sesión en Docker Hub usando los secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Paso 6: Crear el archivo .env dinámicamente a partir del secret
      - name: Create .env file
        run: echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" > .env

      # Paso 7: Construye la imagen de Docker y la sube a Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gastronomic-ai-agent:latest